### ISSUE TITLE
Add downloads for previous versions (1.17, 1.18, 1.19, any version before latest)

### ISSUE THREAD

**Issue by MrKeynesWillis** [theminecraftarchitect/Minecraft-Console-Edition-Tutorial-Worlds#2]
There's may be some oddities when loading a latest world from 1.20 into 1.19. Can you please add download links for previous versions of Minecraft? It would be helpful for Quartz's Console. Thanks.

**Comment by MrKeynesWillis** [comment]
*But not that old like 1.8, 1.13, not those. Just any versions from 1.16 to above.

**Comment by theminecraftarchitect** [comment]
I will try to get this done around Thanksgiving!

**Comment by theminecraftarchitect** [comment]
Available now on the download pages!
