### ISSUE TITLE
Spawning in void

### ISSUE THREAD

**Issue by NotMePipe** [theminecraftarchitect/Minecraft-Console-Edition-Tutorial-Worlds#3]
Every time I load the TU9 Tutorial World for the first time, I spawn in the void. After dying, I spawn back where I am supposed to, but the initial death is very annoying

**Comment by theminecraftarchitect** [comment]
Hey, I believe this is actually a bug with Minecraft itself that has been fixed with the 1.20.5 update - I have tested the worlds with this version and spawning seems to work correctly. Let me know if you are still experiencing issues!

**Comment by theminecraftarchitect** [comment]
Resolved
